image: maven:3.6.3-jdk-11

stages:
  - maven:build
  - maven:test
  - docker:build
  - deploy

maven:build:
  stage: maven:build
  script: 
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

maven:test:
  stage: maven:test
  script: 
    - mvn verify

docker:build:
  image: docker:latest
  services:
    - docker:dind
  stage: docker:build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  script: 
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker run -d -p 8080:8080 $CI_REGISTRY_IMAGE:latest
