apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  labels:
    app: wp
spec:
  selector:
    matchLabels:
      app: wp
  replicas: 2
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
      - name: wp
        image: wordpress:5.8.1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: wp-cfg
          - secretRef:
              name: wp-secrets
              
