pipeline {
    agent any

    stages {
        stage('Verify') {
            steps {
                sh ''' 
                ls -lah
                '''
                sh 'printenv | sort'

            }
        }
        stage('Build') {
            steps {
                dir("modulo4/exercises/jenkins-resources/calculator")
                sh '''
                gradlew compileJava
                              
                '''
            }
        }

        stage('Tests') {
            steps {
                dir("modulo4/exercises/jenkins-resources/calculator")
                sh '''
                gradlew test
                '''
            }
        }
    }
}

