#método de CI job permissions model

clone_repo:
  image: docker:20.10
  script:
    - apk add --no-cache git
    - git config --global url."http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.local:8888/".insteadOf "http://gitlab.local:8888/"
    - git clone http://gitlab.local:8888/bootcamp/cicd_springapp.git


