name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: cd hangman-front && npm install

    - name: Build
      run: cd hangman-front && npm run build

    - name: Run tests
      run: cd hangman-front && npm test

    - name: Convert repository owner to lower case
      run: echo "REPOSITORY_OWNER=$(echo "${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

    - name: Convert repository to lower case
      run: echo "REPOSITORY=$(echo "${{ github.repository }}" | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./hangman-front
        push: true
        tags: ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY }}/hangman-front:latest
